[BitTorrent]
Session\DefaultSavePath=/data/downloads/complete
Session\GlobalMaxRatio=0
Session\MaxRatioAction=0
Session\TempPath=/data/downloads/incomplete
Session\TempPathEnabled=true

[Preferences]
Downloads\SavePath=/data/downloads/complete
Downloads\TempPath=/data/downloads/incomplete
Downloads\TempPathEnabled=true
WebUI\ServerDomains=*
