[BitTorrent]
Session\DefaultSavePath=/downloads/complete
Session\TempPath=/downloads/incomplete
Session\TempPathEnabled=true

[Preferences]
Downloads\SavePath=/downloads/complete
Downloads\TempPath=/downloads/incomplete
Downloads\TempPathEnabled=true
WebUI\ServerDomains=*
